export const MATERIAL_ISSUE_CATEGORY = 'MATERIAL_ISSUE_CATEGORY';
export const META_MATERIAL_ISSUE_ECONOMICS = 'META_MATERIAL_ISSUE_ECONOMICS';
export const META_MATERIAL_ISSUE_ENVIRONMENT = 'META_MATERIAL_ISSUE_ENVIRONMENT';
export const META_MATERIAL_ISSUE_GOVERNANCE = 'META_MATERIAL_ISSUE_GOVERNANCE';
export const META_MATERIAL_ISSUE_SOCIAL = 'META_MATERIAL_ISSUE_SOCIAL';
export const DASHBOARD_GET_DATA = 'DASHBOARD_GET_DATA';
export const MATERIAL_ISSUE_CHILD = 'MATERIAL_ISSUE_CHILD';
export const STATIC_FILTER = 'STATIC_FILTER';
