export const PROJECT_PHASE_NAMES = 'PROJECT_PHASE_NAMES';
export const PROJECT_PHASE_YEARS = 'PROJECT_PHASE_YEARS';
export const STATIONARY_TABLE_POST_DATA = 'STATIONARY_TABLE_POST_DATA';
export const STATIONARY_TABLE_GET_DATA = 'STATIONARY_TABLE_GET_DATA';
export const DELETE_TABLE_DATA = 'DELETE_TABLE_DATA';
export const UPDATE_TABLE_DATA = 'UPDATE_TABLE_DATA';
export const WATER_CALCULATE_POST_DATA = 'WATER_CALCULATE_POST_DATA';
export const QUESTION_TOGGLE = 'QUESTION_TOGGLE';
